name: sls deploy

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    name: sls deploy to Azure
    steps:
    - uses: serverless/sls-action@v0.1.0
    - name: Runs Serverless Action
    - if: github.event.pull_request.merged
      with:
        slsVersion: latest
        slsCommand: deploy
        yamlFile: serverless-azure.yml
        azureSubId: d36d0808-a967-4f73-9fdc-32ea232fc81d
        azurePrefix: pelittle
        region: centralus
        stage: test
